# Generated by Django 3.2.11 on 2022-02-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_customuser_username'),
        ('events', '0034_auto_20220213_1445'),
    ]

    operations = [
    ]
