# Generated by Django 3.2.11 on 2022-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emails',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
