# Generated by Django 3.2.11 on 2022-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20220214_0754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emails',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
