# Generated by Django 3.2.11 on 2022-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_auto_20220214_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='userevent',
            name='is_booked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
