# Generated by Django 3.2.11 on 2022-02-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20220214_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
