# Generated by Django 3.2.11 on 2022-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_booked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
