# Generated by Django 3.2.11 on 2022-02-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_event_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_booked',
        ),
    ]
