# Generated by Django 3.2.11 on 2022-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_remove_event_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='events/media'),
        ),
    ]
